apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydjango-deploy
spec:
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 25%
  #   type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: mydjango-deploy
  template:
    metadata:
      labels:
        app: mydjango-deploy
      annotations:
        kubernetes.io/change-cause: version 0.4
    spec:
      containers:
      - name: myapp
        image: 2e16jun/mydjango:0.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000